name: LogBox
repository: https://github.com/robzimpulse/log_box

packages:
  - packages/**
  - example

ide:
  intellij:
    enabled: false

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:

  refresh:
    description: Refresh all packages dependencies.
    run: melos clean && melos clean:flutter && melos bs && melos get

  clean:flutter:
    description: Clean all packages.
    run: flutter clean
    exec:
      concurrency: 5
      failFast: true
      orderDependents: true

  get:
    description: Get dependencies for all packages.
    run: flutter pub get
    exec:
      concurrency: 5
      failFast: true
      orderDependents: true

  test:
    description: Test for all packages.
    run: flutter test
    exec:
      concurrency: 5
      failFast: true
      orderDependents: true
    packageFilters:
      dirExists: "test"

  upgrade:
    description: Upgrade dependencies for all packages.
    run: flutter pub upgrade
    exec:
      concurrency: 5
      failFast: true
      orderDependents: true

  generate:
    description: Generate files for all packages.
    run: flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 5
      failFast: true
      orderDependents: true
    packageFilters:
      dependsOn: "build_runner"